import ChooseUs from "./ChooseUs";
import OurClients from "./OurClients";
import OurSite from "./OurSite";
import OurTeam from "./OurTeam";

// tab title 
export const metadata = {
  title: "Pet-City | about",
  description: "Generated by create next app",
};

const page = () => {
      return (
            <>
                  <OurSite/>
                  <ChooseUs/>
                  <OurTeam/>
                  <OurClients/>
            </>
      );
};

export default page;